name: "from_spatialdata_to_h5mu"
namespace: "convert"
description: |
  Reads in the Tables field stored in a SpatialData object and converts it to an h5mu file.
    
authors:
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [ maintainer ]
  - __merge__: /src/authors/weiwei_schultz.yaml
    roles: [ contributor ]
arguments:
  - name: "--input"
    alternatives: ["-i"]
    type: file
    description: Input zarr folder where the SpatialData object is stored.
    example: input.zarr
    direction: input
    required: true
  - name: "--modality"
    type: string
    default: rna
  - name: "--output"
    alternatives: ["-o"]
    type: file
    description: The output h5mu file.
    example: "output.h5mu"
    direction: output
  - name: "--output_compression"
    type: string
    choices: ["gzip", "lzf"]
    required: false
    example: "gzip"
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py
test_resources:
  - type: python_script
    path: test.py
  - path: /resources_test/xenium/xenium_tiny.zarr
engines:
  - type: docker
    image: python:3.12-trixie
    setup:
      - type: apt
        packages: 
          - procps
      - type: python
        packages:
          - spatialdata~=0.4.1rc
          - spatialdata-io~=0.2.0
          - mudata~=0.3.1
    test_setup:
      - type: apt
        packages:
          - git
      - type: python
        packages:
          - viashpy==0.8.0
        github: openpipelines-bio/core#subdirectory=packages/python/openpipeline_testutils
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowmem, singlecpu]
