name: concatenate_spatialdata
namespace: dataflow
scope: public
description: |
  Concatenate multiple SpatialData objects into one SpatialData output.

authors:
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [ maintainer ]
  - __merge__: /src/authors/luke_zappia.yaml
    roles: [ author ]

argument_groups:
  - name: Inputs
    arguments:
      - name: --inputs
        type: file
        multiple: true
        multiple_sep: ","
        required: true
        description: |
          Paths to Zarr stores containing the SpatialData objects to concatenate.

  - name: Outputs
    arguments:
      - name: --output
        type: file
        direction: output
        default: output.zarr
        required: true
        description: |
          The output Zarr store containing the concatenated SpatialData object.

  - name: SpatialData options
    description: |
      Options for how to concatenate the SpatialData objects, passed to
      `spatialdata.concatenate`.
    arguments:
      - name: --attrs_merge
        type: string
        choices: [same, unique, first, only]
        description: |
          The method to use for merging elements in `attrs` when concatenating
          the SpatialData objects. See `anndata_merge` for options and details.

  - name: AnnData options
    description: |
      Options for how to concatenate the AnnData objects when concatenating the
      main tables of the SpatialData objects using `anndata.concat`.
    arguments:
      - name: --anndata_join
        type: string
        choices: [inner, outer]
        default: inner
        description: |
          The type of join to perform on the AnnData objects when concatenating
          the main tables of the SpatialData objects:

          - "inner": Only variables (genes) that are present in all objects are
            kept.
          - "outer": All variables (genes) that are present in any object are
            kept. Sparse arrays are padded with zeros, other objects are filled
            with missing values.

          See `anndata.concat` for details.
      - name: --anndata_merge
        type: string
        choices: [same, unique, first, only]
        description: |
          The method to use for merging elements that are not aligned with `obs`
          when concatenating the main tables of the SpatialData objects:

          - None: No elements are kept.
          - "same": Only elements that are the same across all objects are kept.
          - "unique": Elements for which there is only one possible value are
            kept.
          - "first": The first element at each position is kept.
          - "only": Elements that are only in one object are kept.

          See `anndata.concat` for details.
      - name: --anndata_uns_merge
        type: string
        choices: [same, unique, first, only]
        description: |
          The method to use for merging elements in `uns` when concatenating the
          main tables of the SpatialData objects. See `anndata_merge` for
          options and details. Merging is applied recursively.
      - name: --anndata_label
        type: string
        example: sample
        description: |
          The name of the column in `obs` of the concatenated main table to
          store batch label information. If not provided, no batch label column
          is added.
      - name: --anndata_pairwise
        type: boolean
        default: false
        description: |
          Whether pairwise elements (`obsp`/`varp`) are concatenated.

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py

test_resources:
  - type: python_script
    path: test.py
  - path: /resources_test/xenium/xenium_tiny.zarr

engines:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        __merge__: [/src/base/requirements/spatialdata.yaml, /src/base/requirements/anndata.yaml]
    __merge__: [/src/base/requirements/python_test_setup.yaml, .]
  - type: native

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [singlecpu, lowmem, lowdisk]
