name: viash test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: pre-commit/action@v3.0.1

  test:
    uses: viash-io/viash-actions/.github/workflows/test.yaml@v6